version: '3'

services:
  web:
    build: .
    command: >
      gunicorn translation.wsgi:application
      --bind 0.0.0.0:8000
      --certfile /etc/letsencrypt/live/djangoapi.drlugha.com/fullchain.pem
      --keyfile /etc/letsencrypt/live/djangoapi.drlugha.com/privkey.pem
      --workers 3
      --preload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
